services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    api:
        build:
            dockerfile: docker/api/Dockerfile
            context: ../
        ports:
            - 9000:9000
        environment:
            - RUNNING_MODE=production
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - DB_PORT=5432
        depends_on:
            - "db"

    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ../interface:/var/www/html/
            - ./interface/nginx.conf:/etc/nginx/nginx.conf
            - ./interface/urls.js:/var/www/html/static/js/urls.js
        depends_on:
            - "api"
